spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sampleZeroOne
    username: sampleZeroOne
    password: 123
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://dpg-d26ccdnfte5s73emt2lg-a.oregon-postgres.render.com:5432/sample_db_5xtj
#    username: sample_db_5xtj_user
#    password: 3PaN0C2gH3BGKj7nndimvbxsM5BkxeQn
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    uz.shukrullaev.com.sample: DEBUG
