spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/sampleZeroOne
#    username: sampleZeroOne
#    password: 123
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d26ccdnfte5s73emt2lg-a:5432/sample_db_5xtj
    username: sample_db_5xtj_user
    password: 3PaN0C2gH3BGKj7nndimvbxsM5BkxeQn

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    uz.shukrullaev.com.sample: DEBUG
